config/routes.rb
Rails.application.routes.draw do
  get 'locations/all_locations'

  get 'locations/show_location'

  get 'test' => 'welcome#test'

  get 'index' => 'welcome#index'

  post 'index' => 'welcome#index'

  post 'save_location' => 'locations#save_location'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
def locs
	@locations = Locations.all
end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def all_locations
  	@locations = Locations.all
  end

  def show_location
  	@location = Location.find(params[:location_id])
  end

  def save_location
  	Location.new(city: [params: :city], state: [params: :state])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def all_locations
  	@locations = Locations.all
  end

  def test
  	response = HTTParty.get("http://api.wunderground.com/api/#{ENV['weather_api']}/geolookup/conditions/q/NC/Asheville.json")

  	@location = response['location']['city']
  	@temp_f = response['current_observation']['temp_f']
  	@temp_c = response['current_observation']['temp_c']
  	@weather_icon = response['current_observation']['icon_url']
  	@weather_words = response['current_observation']['weather']
  	@forecast_link = response['current_observation']['forecast_url']
  	@real_feel = response['current_observation']['feelslike_f']
  end

  def index
  	# Creates an array of states that our user can choose from on our index page
    @states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB KS OK 
         TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY 
         NJ CT RI MA VT NH ME DC).sort!
    # removes spaces from the 2-word city names and replaces the space with an underscore 
      if params[:city] != nil
          params[:city].gsub!(" ", "_")
      end
    #checks that the state and city params are not empty before calling the API
      if params[:state] != "" && params[:city] != "" && params[:state] != nil && params[:city] != nil
         
     results = HTTParty.get("http://api.wunderground.com/api/#{ENV['weather_api']}/geolookup/conditions/q/#{params[:state]}/#{params[:city]}.json")
          
           #if no error is returned from the call, we fill our instants variables with the result of the call
        if results['response']['error'] == nil || results['error'] ==""
    
        #Checks to see if the response contains an array (ambigous response for an invalid city/state combination) or a hash(valid response)
            if results.key?("location") 
	            @location = results['location']['city']
	            @temp_f = results['current_observation']['temp_f']
	            @temp_c = results['current_observation']['temp_c']
	            @weather_icon = results['current_observation']['icon_url']
	            @weather_words = results['current_observation']['weather']
	            @forecast_link = results['current_observation']['forecast_url']
	            @real_feel_f = results['current_observation']['feelslike_f']
	            @real_feel_c = results['current_observation']['feelslike_c']
            else
	            @error = "City/State combination does not exist." 
	        end     
          else
         # if there is an error, we report it to our user via the @error variable   
            @error = results['response']['error']['description']
          end
           
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
	</div>
  </body>
</html>

app/views/locations/all_locations.html.erb
<h1>Locations#all_locations</h1>
<p>Find me in app/views/locations/all_locations.html.erb</p>

app/views/locations/show_location.html.erb
<h1>Locations#show_location</h1>
<p>Find me in app/views/locations/show_location.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<% if !@location.nil? && @error.nil? %>
				<div class="row">
					<div class="col-md-7">
						<p><em>Weather</em></p>
						<p>
							Temp: <%= @temp_f %> F / <%= @temp_c %> C
						</p>
						<p>
							Feels like: <%= @real_feel_f %> F
						</p>
					</div>
					<div class="col-md-5">
						<p>
							<%= @weather_words %> <%= image_tag @weather_icon %>
						</p>
						<p>
							<%= link_to "Full Forecast", @forecast_link, target: "blank" %>
						</p>
					</div>
				</div>
				<div>
				<%= link_to "Save Location", save_location_path(location_id: :location_id) %>
				</div>
			<% else %>
				<p>
					Error: Please enter a valid location. <%= @error %> 
				</p>

			<% end %>
		</div>
	</div>


</div>


<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<h1>Look up the weather forecast:</h1>
			<div>
				<%= form_tag index_path do %>
					<%= text_field_tag :city, nil, placeholder: "City", class:"form-control" %>
					<br>
					<%= select_tag :state, options_for_select(@states), prompt:"Please select" %>
					<br>
					<%= submit_tag "Check Weather!", class:"btn btn-primary" %>

				<% end %>
			</div>
		</div>
	</div>
</div>

<div>
	<p>
		Saved locations:
	</p>
	<ul>
		<% if @location != nil %>
			<%= @location.each do |location| %>
				<li><%= link_to location.city.upcase location.state.upcase, show_location_path(location_id: :location_id) >%
				</li>
			<% end %>
		<% end %>
	</ul>

</div>
<% end -%>

app/views/welcome/test.html.erb
<h1>Weather</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<div class="row">
				<div class="col-md-7">
					<p><em>Weather</em></p>
					<p>
						Temp: <%= @temp_f %> F / <%= @temp_c %> C
					</p>
					<p>
						Feels like: <%= @real_feel %> F
					</p>
				</div>
				<div class="col-md-5">
					<p>
						<%= @weather_words %> <%= image_tag @weather_icon %>
					</p>
					<p>
						<%= link_to "Full Forecast", @forecast_link, target: "blank" %>
					</p>
				</div>
			</div>
		</div>
	</div>


</div>